#ifndef GAME_MESSAGE_ENUM_H
#define GAME_MESSAGE_ENUM_H

enum class OutputMessageVariants {
    INPUT_WIDTH,
    INPUT_HEIGHT,
    INVALID_INPUT,
    INPUT_COORDINATE,
    INVALID_COORDINATE,
    RE_ENTER_COORDINATE,
    ATTACK_COORDINATE,
    SCANNER_COORDINATE,
    OPTION_LOAD_GAME,
    COORDINATE_OUT_OF_RANGE,
    INVALID_COORDINATE_FOR_ATTACK,
    LOST,
    QUES_START_NEW_GAME,
    START_NEW_GAME,
    WIN,
    QUES_START_NEW_ROUND,
    START_NEW_ROUND
};

#endif